### ISSUE TITLE
StatET cannot index lambda.r functions

### ISSUE THREAD

**Issue by cronacronis** [zatonovo/lambda.r#28]
I am a user of [StatET](http://www.walware.de/goto/statet) (I assume a lot of other users) and unfortunately there is no way for StatET to index a defition of a function defined by lambda.r;
Are there any plans to make lambda.r compatible with R syntax? Are there any IDE which support lambda.r syntax?

**Comment by muxspace** [comment]
I only use vim, so I'm not familiar with how the indexing works in StatET nor the use case you're referring to. My guess is that the Eclipse framework is flexible enough so that StatET could support the syntax. It seems like something you would need to take up with the StatET community and see how to support the syntax in their indexing system.

**Comment by cronacronis** [comment]
I will pass it to their mail-list, thanks.

**Comment by muxspace** [comment]
Sorry I couldn't be of more help. If you find out that they need specific things from lambda.r, let me know, and we can explore what's possible.
